name: CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11  # Use Python 3.11 instead of 3.12

      - name: Upgrade Pip, Setuptools, and Wheel
        run: |
          python -m pip install --upgrade pip setuptools wheel

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          pytest  # Modify based on your test framework

      # Deploy to the server via SSH
      - name: Deploy to VM
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.VM_HOST }}             
          username: ${{ secrets.VM_USERNAME }}     
          key: ${{ secrets.VM_SSH_KEY }}         
          port: 22
          script: |
            /home/jd2010/deploy.sh
