name: Deploy on Push to Main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository (for running tests if needed)
      - name: Checkout repository
        uses: actions/checkout@v3

      # Optional: Run tests or linting (for checking/compiling your code)
      - name: Run tests
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          # Run your tests or code checks
          python manage.py test

      # Deploy to the server via SSH
      - name: Deploy to VM
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.VM_HOST }}             # e.g., 34.46.249.7
          username: ${{ secrets.VM_USERNAME }}           # your VM username
          key: ${{ secrets.VM_SSH_KEY }}             # your private SSH key (set in GitHub Secrets)
          port: 22
          script: |
            /home/jd2010/deploy.sh
