name: Deploy on Push to Main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      GEMINI_API_KEY: ${{secrets.GEMINI_API_KEY}}
      BRAVE_API_KEY: ${{secrets.BRAVE_API_KEY}}
      MONGODB_NAME: ${{secrets.MONGODB_NAME}}
      MONGODB_URI: ${{secrets.MONGODB_URI}}
      MONGODB_USERNAME: ${{secrets.MONGODB_USERNAME}}
      MONGODB_PASSWORD: ${{secrets.MONGODB_PASSWORD}}
      DEBUG: ${{secrets.DEBUG}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create .env file
        run: |
          echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" > .env
          echo "BRAVE_API_KEY=${{ secrets.BRAVE_API_KEY }}" >> .env
          echo "MONGODB_NAME=${{ secrets.MONGODB_NAME }}" >> .env
          echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> .env
          echo "MONGODB_USERNAME=${{ secrets.MONGODB_USERNAME }}" >> .env
          echo "MONGODB_PASSWORD=${{ secrets.MONGODB_PASSWORD }}" >> .env
          echo "DEBUG=${{ secrets.DEBUG }}" >> .env

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Upgrade pip, setuptools, and wheel
        run: |
          python -m pip install --upgrade pip setuptools wheel

      - name: Install dependencies and run tests
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          # Remove distutils from requirements.txt if it exists
          grep -v "^distutils" requirements.txt > requirements_fixed.txt
          pip install -r requirements_fixed.txt
          python manage.py test

      - name: Deploy to VM
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}
          port: 22
          script: |
            /home/jd2010/deploy.sh
