name: Deploy on Push to Main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install system dependencies including python3-distutils
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-distutils

      # Set up Python environment (adjust python-version if needed)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Create and activate the virtual environment and upgrade pip/setuptools/wheel
      - name: Create virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip setuptools wheel

      # Install Python dependencies from requirements.txt
      - name: Install dependencies
        run: |
          source venv/bin/activate
          pip install -r requirements.txt

      # Optional: Run tests
      - name: Run tests
        run: |
          source venv/bin/activate
          python manage.py test

      # Deploy to the VM via SSH
      - name: Deploy to VM
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.VM_HOST }}         # e.g., 34.46.249.7
          username: ${{ secrets.VM_USERNAME }}   # your VM username
          key: ${{ secrets.VM_SSH_KEY }}         # your SSH private key secret
          port: 22
          script: |
            /home/jd2010/deploy.sh